name: Complete DevSecOps Pipeline with Trivy, Snyk and SonarQube

on:
  push:
    branches:
      - main

jobs:
  trivy-image-scan-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/app-frontend:latest

      - name: Run Trivy Image Scan - Frontend
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/app-frontend:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

  trivy-image-scan-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/app-backend:latest

      - name: Run Trivy Image Scan - Backend
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/app-backend:latest''
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

  trivy-scan-mongo:
    runs-on: ubuntu-latest

    steps:
      - name: Trivy Scan - MongoDB
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'mongo:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            set -e
            cd /home/ubuntu/Launchpad
            git pull
            docker compose up -d --build
